package com.azim.vdub

import com.azim.vdub.audio.NpzReader
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * DhVaani ships its mel filterbank and Vocos ISTFT head as numpy archives, so
 * these have to be read correctly or the voice is subtly wrong rather than
 * broken — the wrong filterbank still produces audio, just of a different
 * speaker.
 *
 * The fixtures here are written byte-by-byte in the .npy format rather than
 * generated by numpy, since the test has to run without it.
 */
class NpzReaderTest {

    private fun npy(
        shape: IntArray,
        dtype: String,
        writeData: (ByteBuffer) -> Unit,
        elementBytes: Int,
        version: Int = 1
    ): ByteArray {
        val shapeText = when (shape.size) {
            0 -> "()"
            1 -> "(${shape[0]},)"
            else -> "(" + shape.joinToString(", ") + ")"
        }
        var header = "{'descr': '$dtype', 'fortran_order': False, 'shape': $shapeText, }"
        val prefix = 6 + 2 + (if (version >= 2) 4 else 2)
        while ((prefix + header.length + 1) % 64 != 0) header += " "
        header += "\n"

        val count = if (shape.isEmpty()) 1 else shape.fold(1) { a, b -> a * b }
        val out = ByteArrayOutputStream()
        out.write(byteArrayOf(0x93.toByte()))
        out.write("NUMPY".toByteArray())
        out.write(version)          // major
        out.write(0)                // minor
        if (version >= 2) {
            out.write(ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN)
                .putInt(header.length).array())
        } else {
            out.write(ByteBuffer.allocate(2).order(ByteOrder.LITTLE_ENDIAN)
                .putShort(header.length.toShort()).array())
        }
        out.write(header.toByteArray())

        val body = ByteBuffer.allocate(count * elementBytes).order(ByteOrder.LITTLE_ENDIAN)
        writeData(body)
        out.write(body.array())
        return out.toByteArray()
    }

    private fun zip(entries: Map<String, ByteArray>): File {
        val f = File.createTempFile("test", ".npz")
        f.deleteOnExit()
        ZipOutputStream(f.outputStream()).use { zos ->
            entries.forEach { (name, bytes) ->
                zos.putNextEntry(ZipEntry(name))
                zos.write(bytes)
                zos.closeEntry()
            }
        }
        return f
    }

    @Test
    fun `reads a float32 matrix in row-major order`() {
        val file = zip(mapOf(
            "fb.npy" to npy(intArrayOf(2, 3), "<f4", { b ->
                floatArrayOf(1f, 2f, 3f, 4f, 5f, 6f).forEach { b.putFloat(it) }
            }, 4)
        ))
        val arr = NpzReader.read(file).getValue("fb")
        assertEquals(listOf(2, 3), arr.shape.toList())

        val m = arr.as2D()
        assertEquals(1f, m[0][0], 1e-6f)
        assertEquals(3f, m[0][2], 1e-6f)
        assertEquals(4f, m[1][0], 1e-6f)
        assertEquals(6f, m[1][2], 1e-6f)
    }

    /** n_fft / hop_length / win_length arrive as rank-0 int64 scalars. */
    @Test
    fun `reads a rank zero int64 scalar`() {
        val file = zip(mapOf(
            "n_fft.npy" to npy(intArrayOf(), "<i8", { it.putLong(1024L) }, 8)
        ))
        assertEquals(1024f, NpzReader.read(file).getValue("n_fft").scalar, 0f)
    }

    @Test
    fun `reads float64 by narrowing`() {
        val file = zip(mapOf(
            "w.npy" to npy(intArrayOf(2), "<f8", { b ->
                b.putDouble(0.5); b.putDouble(-1.25)
            }, 8)
        ))
        val d = NpzReader.read(file).getValue("w").data
        assertEquals(0.5f, d[0], 1e-6f)
        assertEquals(-1.25f, d[1], 1e-6f)
    }

    /** Larger headers use the v2 4-byte length; both must parse. */
    @Test
    fun `reads a version 2 header`() {
        val file = zip(mapOf(
            "v.npy" to npy(intArrayOf(3), "<f4", { b ->
                b.putFloat(7f); b.putFloat(8f); b.putFloat(9f)
            }, 4, version = 2)
        ))
        assertEquals(9f, NpzReader.read(file).getValue("v").data[2], 1e-6f)
    }

    @Test
    fun `keys drop the npy suffix and all entries are returned`() {
        val file = zip(mapOf(
            "linear_weight.npy" to npy(intArrayOf(1), "<f4", { it.putFloat(1f) }, 4),
            "linear_bias.npy" to npy(intArrayOf(1), "<f4", { it.putFloat(2f) }, 4),
            "window.npy" to npy(intArrayOf(1), "<f4", { it.putFloat(3f) }, 4)
        ))
        val m = NpzReader.read(file)
        assertEquals(setOf("linear_weight", "linear_bias", "window"), m.keys)
    }

    /** A half-downloaded archive must be reported, not read as short data. */
    @Test
    fun `a truncated file is rejected`() {
        val f = File.createTempFile("bad", ".npz")
        f.deleteOnExit()
        f.writeBytes(byteArrayOf(0x50, 0x4B, 0x03, 0x04, 0x00))
        assertThrows(Exception::class.java) { NpzReader.read(f) }
    }

    @Test
    fun `a missing file is reported by name`() {
        val f = File("/nonexistent/mel_fb.npz")
        val e = assertThrows(IllegalArgumentException::class.java) { NpzReader.read(f) }
        assertTrue(e.message!!.contains("mel_fb.npz"))
    }

    /** Big-endian data would be read as garbage, so it must throw instead. */
    @Test
    fun `big endian is rejected rather than misread`() {
        val file = zip(mapOf(
            "x.npy" to npy(intArrayOf(1), ">f4", { it.putFloat(1f) }, 4)
        ))
        assertThrows(Exception::class.java) { NpzReader.read(file) }
    }
}
